/**
 * Post-Processing Pipeline
 * Performs automated post-translation validation, test stub generation, and diff analysis.
 */

export function postProcessTranslation({ translatedCode, sourceLang, targetLang, options = {}, astData = {} }) {
  // 1. Basic Syntax Integrity Validation
  const syntaxErrors = validateSyntaxBasic(translatedCode, targetLang);
  
  // 2. Automated Unit Test Stub Generator
  let testStubs = '';
  if (options.includeTests) {
    testStubs = generateUnitTestStubs(translatedCode, targetLang, astData);
  }

  // 3. Diff Matrix Computation
  const lineStats = {
    sourceLines: 0,
    targetLines: translatedCode.split('\n').length,
    characterCount: translatedCode.length,
  };

  return {
    cleanedCode: translatedCode,
    syntaxErrors,
    isValid: syntaxErrors.length === 0,
    testStubs,
    lineStats,
  };
}

function validateSyntaxBasic(code, lang) {
  const errors = [];
  const normalizedLang = lang.toLowerCase();

  // Mismatched brackets check
  const stack = [];
  const brackets = { '(': ')', '{': '}', '[': ']' };
  
  for (let i = 0; i < code.length; i++) {
    const char = code[i];
    if (brackets[char]) {
      stack.push(char);
    } else if (Object.values(brackets).includes(char)) {
      const last = stack.pop();
      if (!last || brackets[last] !== char) {
        errors.push(`Unmatched bracket '${char}' around character index ${i}`);
        break;
      }
    }
  }

  if (normalizedLang === 'python') {
    // Check python indentation / colon consistency
    const lines = code.split('\n');
    lines.forEach((line, idx) => {
      if (line.trim().startsWith('def ') || line.trim().startsWith('if ') || line.trim().startsWith('for ')) {
        if (!line.trim().endsWith(':') && !line.includes('#')) {
          errors.push(`Line ${idx + 1}: Python statement missing ending colon ':'`);
        }
      }
    });
  }

  return errors;
}

function generateUnitTestStubs(translatedCode, targetLang, astData) {
  const tLang = targetLang.toLowerCase();
  const functions = astData.functions || [];
  const fnNames = functions.map(f => f.name).filter(n => n !== 'anonymous');

  if (tLang === 'python') {
    return `import pytest
# Unit Test Suite generated by Smart Code Translator (PyTest)

${fnNames.length > 0 ? fnNames.map(fn => `
def test_${fn}_default():
    # TODO: Add assertions for ${fn}
    # result = ${fn}()
    # assert result is not None
    pass
`).join('') : `
def test_sample():
    assert True
`}
`;
  }

  if (tLang === 'javascript' || tLang === 'typescript') {
    return `import { describe, it, expect } from 'vitest';
// Unit Test Suite generated by Smart Code Translator (Vitest / Jest)

describe('Translated Code Unit Tests', () => {
${fnNames.length > 0 ? fnNames.map(fn => `  it('should execute ${fn} correctly', () => {
    // TODO: Pass test parameters to ${fn}
    // const result = ${fn}();
    // expect(result).toBeDefined();
  });`).join('\n') : `  it('sample test', () => {
    expect(true).toBe(true);
  });`}
});
`;
  }

  if (tLang === 'java') {
    return `import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class GeneratedCodeTest {

${fnNames.length > 0 ? fnNames.map(fn => `    @Test
    void test${capitalize(fn)}() {
        // TODO: Assert ${fn} execution
        assertTrue(true);
    }`).join('\n\n') : `    @Test
    void testSample() {
        assertTrue(true);
    }`}
}
`;
  }

  if (tLang === 'go') {
    return `package main

import (
\t"testing"
)

// Unit Test Suite generated by Smart Code Translator (Go testing)

${fnNames.length > 0 ? fnNames.map(fn => `func Test${capitalize(fn)}(t *testing.T) {
\t// TODO: Add unit test logic for ${fn}
\tif false {
\t\tt.Errorf("${fn} failed")
\t}
}`).join('\n\n') : `func TestSample(t *testing.T) {
\t// Basic sanity check
}`}
`;
  }

  return `// Automated Unit Test Stub for ${targetLang}
// Verify target logic and assertions
`;
}

function capitalize(str) {
  if (!str) return 'Function';
  return str.charAt(0).toUpperCase() + str.slice(1);
}
